//! Deterministic benchmark workloads.
//!
//! A scenario builds an initial engine state (seeded resting book) and a
//! state-aware op stream. The stream is generated by *running* it once, so
//! every cancel targets an order id that exists at that point; replaying the
//! same stream on a clone of the initial engine reproduces the same state
//! (the engine is deterministic and both ladders produce identical ids).

use crate::engine::*;
use crate::num::Num;
use crate::Ladder;

#[derive(Clone, Copy, Debug)]
pub enum Op {
    Place(PlaceOrder),
    Cancel(UserId, OrderId),
    Expire,
}

#[inline(always)]
pub fn apply<L: Ladder>(e: &mut Engine<L>, op: &Op) -> usize {
    match op {
        Op::Place(p) => match e.place_order(p) {
            Ok(r) => r.n_fills,
            Err(_) => 0,
        },
        Op::Cancel(u, id) => {
            let _ = e.cancel_order(*u, *id);
            0
        }
        Op::Expire => {
            e.expire(5000);
            0
        }
    }
}

pub struct Rng(pub u64);
impl Rng {
    #[inline]
    pub fn next(&mut self) -> u64 {
        // xorshift64*
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0.wrapping_mul(0x2545F4914F6CDD1D)
    }
    #[inline]
    pub fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }
    #[inline]
    pub fn chance(&mut self, p: f64) -> bool {
        ((self.next() >> 11) as f64 / (1u64 << 53) as f64) < p
    }
    #[inline]
    pub fn range(&mut self, lo: i64, hi: i64) -> i64 {
        lo + self.below((hi - lo + 1) as u64) as i64
    }
}

#[derive(Clone, Copy, Debug)]
pub struct Mix {
    pub passive: f64,
    pub cross: f64,
    pub market: f64,
    pub cancel: f64,
    pub sell: f64,
    pub expire: f64,
    /// target resting orders per book
    pub depth: usize,
    /// passive price band width (deci-cents) on each side of mid
    pub band: i64,
    pub size_max: i64,
    pub market_size: (i64, i64),
    pub tick_deci: i64,
}

pub struct Scenario<L: Ladder> {
    pub name: &'static str,
    pub init: Engine<L>,
    pub ops: Vec<Op>,
}

pub const SCENARIOS: [&str; 5] = ["shallow", "deep3000", "sweep", "cancel_heavy", "mixed"];

pub fn mix_for(name: &str) -> (Mix, usize /*books*/, usize /*markets*/) {
    let base = Mix {
        passive: 0.45,
        cross: 0.2,
        market: 0.1,
        cancel: 0.2,
        sell: 0.05,
        expire: 0.0,
        depth: 60,
        band: 60,
        size_max: 20,
        market_size: (5, 40),
        tick_deci: 10,
    };
    match name {
        "shallow" => (base, 2, 1),
        "deep3000" => (Mix { passive: 0.5, cross: 0.12, market: 0.05, cancel: 0.3, sell: 0.03, depth: 3000, band: 400, tick_deci: 1, ..base }, 1, 1),
        "sweep" => (Mix { passive: 0.9, cross: 0.0, market: 0.1, cancel: 0.0, sell: 0.0, depth: 1500, band: 100, size_max: 3, market_size: (100, 300), tick_deci: 1, ..base }, 1, 1),
        "cancel_heavy" => (Mix { passive: 0.5, cross: 0.0, market: 0.0, cancel: 0.5, sell: 0.0, depth: 3000, band: 10, tick_deci: 1, ..base }, 1, 1),
        "mixed" => (Mix { passive: 0.4, cross: 0.18, market: 0.12, cancel: 0.2, sell: 0.08, expire: 0.02, depth: 200, band: 150, tick_deci: 1, ..base }, 4, 2),
        _ => panic!("unknown scenario {name}"),
    }
}

pub fn engine_config() -> Config {
    Config { keep_history: false, rate_limit: false, max_open_per_user: 250, max_open_per_user_market: 60 }
}

const USERS: u32 = 256;
const MID: i64 = 500;

struct Gen {
    r: Rng,
    m: Mix,
    nbooks: u32,
    live: Vec<Vec<(OrderId, UserId)>>,
}

impl Gen {
    fn size(&mut self) -> Num {
        let s = self.r.range(1, self.m.size_max);
        if self.r.chance(0.2) { Num::new(s as i128 * 10 + 5, 1) } else { Num::new(s as i128, 0) }
    }
    fn snap(&self, px: i64) -> i64 {
        let t = self.m.tick_deci;
        ((px / t) * t).clamp(t.max(1), 999 / t * t)
    }
    /// A place op for `book`; `cross` = aggressive limit through the mid.
    fn limit<L: Ladder>(&mut self, e: &Engine<L>, book: u32, cross: bool, sell: bool) -> Option<PlaceOrder> {
        let user = self.r.below(USERS as u64) as u32;
        let bid = self.r.chance(0.5); // YES-perspective side of the new order
        let off = if cross { -self.r.range(1, 60) } else { self.r.range(1, self.m.band) };
        let yes_px = self.snap(if bid { MID - off } else { MID + off });
        // bid = buy YES or sell NO ; ask = sell YES or buy NO
        let (outcome, action) = match (bid, sell) {
            (true, false) => (Outcome::Yes, Action::Buy),
            (true, true) => (Outcome::No, Action::Sell),
            (false, false) => (Outcome::No, Action::Buy),
            (false, true) => (Outcome::Yes, Action::Sell),
        };
        let own_px = if outcome == Outcome::Yes { yes_px } else { 1000 - yes_px };
        let mut size = self.size();
        if sell {
            let p = e.position(user, book, outcome);
            let avail = p.shares - p.reserved_shares;
            if avail < 1_000_000 {
                return None;
            }
            size = Num::new((avail / 2).max(1_000_000), 6);
        }
        Some(PlaceOrder {
            user,
            book,
            outcome,
            action,
            otype: OrderType::Limit,
            price: Some(Num::new(own_px as i128, 1)),
            size,
            max_spend_usd: None,
            expires_at: if self.r.chance(self.m.expire) { Some(0) } else { None },
        })
    }
    fn market(&mut self, book: u32) -> PlaceOrder {
        let user = self.r.below(USERS as u64) as u32;
        let (lo, hi) = self.m.market_size;
        let size = Num::new(self.r.range(lo, hi) as i128, 0);
        let outcome = if self.r.chance(0.5) { Outcome::Yes } else { Outcome::No };
        let spend = if self.r.chance(0.5) { Some(Num::new(self.r.range(100, 5000) as i128, 2)) } else { None };
        PlaceOrder { user, book, outcome, action: Action::Buy, otype: OrderType::Market, price: None, size, max_spend_usd: spend, expires_at: None }
    }
    fn resting<L: Ladder>(e: &Engine<L>, b: u32) -> usize {
        e.ladder.resting(b, crate::BookSide::Bid) + e.ladder.resting(b, crate::BookSide::Ask)
    }
    fn cancel<L: Ladder>(&mut self, e: &Engine<L>, b: u32) -> Option<Op> {
        let l = &mut self.live[b as usize];
        while !l.is_empty() {
            let i = self.r.below(l.len() as u64) as usize;
            let (id, u) = l[i];
            match e.order(id) {
                Some(o) if o.status.live() => {
                    l.swap_remove(i);
                    return Some(Op::Cancel(u, id));
                }
                _ => {
                    l.swap_remove(i);
                }
            }
        }
        None
    }
    fn next_op<L: Ladder>(&mut self, e: &Engine<L>) -> Op {
        loop {
            let b = self.r.below(self.nbooks as u64) as u32;
            let depth = Self::resting(e, b);
            let m = self.m;
            let x = (self.r.next() >> 11) as f64 / (1u64 << 53) as f64;
            let force_cancel = depth > m.depth + m.depth / 10;
            let force_post = depth < m.depth - m.depth / 10;
            if (force_cancel && !force_post) || (!force_post && x < m.cancel) {
                if let Some(op) = self.cancel(e, b) {
                    return op;
                }
                continue;
            }
            let x = if force_post { self.r.below(1000) as f64 / 1000.0 * m.passive } else { x - m.cancel };
            if x < m.passive {
                if let Some(p) = self.limit(e, b, false, false) {
                    return Op::Place(p);
                }
            } else if x < m.passive + m.cross {
                if let Some(p) = self.limit(e, b, true, false) {
                    return Op::Place(p);
                }
            } else if x < m.passive + m.cross + m.market {
                return Op::Place(self.market(b));
            } else if x < m.passive + m.cross + m.market + m.sell {
                let cross = self.r.chance(0.5);
                if let Some(p) = self.limit(e, b, cross, true) {
                    return Op::Place(p);
                }
            } else if m.expire > 0.0 {
                return Op::Expire;
            }
        }
    }
    fn track<L: Ladder>(&mut self, e: &Engine<L>, op: &Op, placed: Option<OrderId>) {
        if let (Op::Place(p), Some(id)) = (op, placed) {
            if e.order(id).map_or(false, |o| o.status.live()) {
                self.live[p.book as usize].push((id, p.user));
            }
        }
    }
}

fn setup<L: Ladder>(nbooks: usize, nmarkets: usize, cap: usize) -> Engine<L> {
    let mut e = Engine::<L>::new(engine_config(), cap);
    e.now = 1_000_000;
    let mkts: Vec<u32> = (0..nmarkets)
        .map(|_| {
            e.add_market(Market {
                tick_size: Num::new(10, 4),
                min_order_size: Num::new(1, 2),
                closes_at: i64::MAX,
                active: true,
            })
        })
        .collect();
    for _ in 0..USERS {
        e.add_user(Wallet { available: 1_000_000_000_000_000, reserved: 0, rate: Num::new(100_000_000, 8) });
    }
    for b in 0..nbooks {
        e.add_option(mkts[b % nmarkets]);
    }
    e
}

/// Build scenario `name` with `nops` ops (seeded, deterministic).
pub fn build<L: Ladder>(name: &'static str, nops: usize, seed: u64) -> Scenario<L> {
    let (m, nbooks, nmarkets) = mix_for(name);
    let cap = m.depth * nbooks * 2 + 4096;
    let mut e: Engine<L> = setup(nbooks, nmarkets, cap);
    let mut g = Gen { r: Rng(seed | 1), m, nbooks: nbooks as u32, live: vec![vec![]; nbooks] };
    // seed the book to the target depth with passive orders
    for b in 0..nbooks as u32 {
        while Gen::resting(&e, b) < m.depth {
            if let Some(p) = g.limit(&e, b, false, false) {
                let op = Op::Place(p);
                let r = e.place_order(&p).ok().map(|r| r.order);
                g.track(&e, &op, r);
            }
        }
    }
    // warm-up (not recorded): reach a steady state incl. positions for sells
    for _ in 0..nops.min(20_000) {
        let op = g.next_op(&e);
        let r = if let Op::Place(p) = op { e.place_order(&p).ok().map(|r| r.order) } else { apply(&mut e, &op); None };
        g.track(&e, &op, r);
    }
    let init = e.clone_reserved();
    let mut ops = Vec::with_capacity(nops);
    for _ in 0..nops {
        let op = g.next_op(&e);
        let r = if let Op::Place(p) = op { e.place_order(&p).ok().map(|r| r.order) } else { apply(&mut e, &op); None };
        g.track(&e, &op, r);
        ops.push(op);
    }
    Scenario { name, init, ops }
}
